package com.example.blogapp2backend.dto.request.post;

import lombok.Data;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.List;

@Data
public class CreatePostRequest {

    @NotBlank(message = "Title is required")
    @Size(min = 5, max = 280, message = "Title must be between 5 and 200 characters")
    private String title;

    @NotBlank(message = "Content is required")
    @Size(min = 10, message = "Content must be at least 10 characters")
    private String content;

    @Size(max = 300, message = "Excerpt cannot exceed 300 characters")
    private String excerpt;

    private List<String> tags;

    private Boolean published = false; // Default to draft

    private String coverImageUrl;

    // Note: No authorId - that comes from the authenticated user
    // Note: No createdAt/updatedAt - those are set by the system
    // Note: No id - that's generated by the database
}
